# Generated by Django 4.2.7 on 2025-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(help_text='Ethereum transaction hash', max_length=200, unique=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('tournament_score', 'Tournament Score'), ('contract_deploy', 'Contract Deployment')], default='tournament_score', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data', models.JSONField(blank=True, help_text='Transaction metadata', null=True)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('gas_price', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contract_type', models.CharField(choices=[('tournament_score', 'Tournament Score Storage')], max_length=30)),
                ('address', models.CharField(help_text='Contract address on blockchain', max_length=200, unique=True)),
                ('abi', models.JSONField(help_text='Contract ABI (Application Binary Interface)')),
                ('bytecode', models.TextField(blank=True, help_text='Contract bytecode', null=True)),
                ('deployment_tx', models.CharField(max_length=200)),
                ('network', models.CharField(default='ganache', help_text='Blockchain network (ganache, testnet, mainnet)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
